Make the installation and import of certificates more robust, if the NSS based security provider is disabled or not built.

diff --git a/pkgs/ca-certificates-java/tags/20100406ubuntu1guada1/debian/postinst b/pkgs/ca-certificates-java/tags/20100406ubuntu1guada1/debian/postinst
--- a/pkgs/ca-certificates-java/tags/20100406ubuntu1guada1/debian/postinst
+++ b/pkgs/ca-certificates-java/tags/20100406ubuntu1guada1/debian/postinst
@@ -61,6 +61,13 @@ first_install()
 			-alias "$alias" -file "$cacertdir/$pem" > $log 2>&1
 		  then
 		      echo "  added certificate $pem"
+		  elif LANG=C LC_ALL=C keytool -importcert -trustcacerts -keystore $KEYSTORE \
+		        -providerClass sun.security.pkcs11.SunPKCS11 \
+		        -providerArg '${java.home}/lib/security/nss.cfg' \
+			-noprompt -storepass "$storepass" \
+			-alias "$alias" -file "$cacertdir/$pem" > $log 2>&1
+		  then
+		      echo "  added certificate $pem (using NSS provider)"
 		  elif grep -q 'Signature not available' $log; then
 		      echo "  ignored import, signature not available: ${line#+*}"
 		      sed -e 's/^/   -> /' $log
@@ -74,7 +81,7 @@ first_install()
     rm -f $log
     rm -f $pregenerated
     if [ $errors -gt 0 ]; then
-	echo >&2 "failed."
+	echo >&2 "failed (VM used: $jvm)."
 	[ -z "$temp_jvm_cfg" ] || rm -f $temp_jvm_cfg
 	exit 1
     fi
@@ -86,6 +93,11 @@ case "$1" in
     configure)
         if [ -z "$2" ]; then
 	    setup_path
+
+	    if ! mountpoint -q /proc; then
+		echo >&2 "the keytool command requires a mounted proc fs (/proc)."
+		exit 1
+	    fi
 
 	    if [ ! -f /etc/$jvm/jvm.cfg ]; then
 		# the jre is not yet configured, but jvm.cfg is needed to run it
