* debian/rules, debian/postinst, debian/jks-keystore.hook: Filter out   SHA384withECDSA certificates since keytool won't support them.   LP: #392104, closes: #534520. * Fix typo in hook. Closes: #534533. * Use java6-runtime-headless as alternative dependency. Closes: #512293.

diff --git a/pkgs/ca-certificates-java/tags/20100406ubuntu1guada1/debian/postinst b/pkgs/ca-certificates-java/tags/20100406ubuntu1guada1/debian/postinst
--- a/pkgs/ca-certificates-java/tags/20100406ubuntu1guada1/debian/postinst
+++ b/pkgs/ca-certificates-java/tags/20100406ubuntu1guada1/debian/postinst
@@ -11,7 +11,7 @@ fi
 
 setup_path()
 {
-    for jvm in java-6-openjdk java-6-sun java-6-cacao; do
+    for jvm in java-6-openjdk java-6-sun; do
 	if [ -x /usr/lib/jvm/$jvm/bin/keytool ]; then
 	    break
 	fi
@@ -23,6 +23,7 @@ setup_path()
 first_install()
 {
     cacertdir=/usr/share/ca-certificates
+    log=$(tempfile)
 
     # aliases of pregenerated files
     pregenerated=$(tempfile)
@@ -55,18 +56,22 @@ first_install()
 		    continue
 		fi
 		if ! grep -q "^${alias}$" $pregenerated; then
-		    if LANG=C LC_ALL=C keytool -importcert -trustcacerts -keystore $KEYSTORE \
+		  if LANG=C LC_ALL=C keytool -importcert -trustcacerts -keystore $KEYSTORE \
 			-noprompt -storepass "$storepass" \
-			-alias "$alias" -file "$cacertdir/$pem"
-		    then
-			echo "  added certificate $pem"
-		    else
-			echo >&2 "  error adding ${line#+*}"
-			errors=$(expr $errors + 1)
-		    fi
+			-alias "$alias" -file "$cacertdir/$pem" > $log 2>&1
+		  then
+		      echo "  added certificate $pem"
+		  elif grep -q 'Signature not available' $log; then
+		      echo "  ignored import, signature not available: ${line#+*}"
+		      cat $log
+		  else
+		      echo >&2 "  error adding ${line#+*}"
+		      errors=$(expr $errors + 1)
+		  fi
 		fi
 	esac
     done
+    rm -f $log
     rm -f $pregenerated
     if [ $errors -gt 0 ]; then
 	echo >&2 "failed."
